context("Test_MultiTopoConst.EditXML4BEAST2")


src.dir = system.file("extdata/TopoConstraints", package = "regPhylo")
dir.create("TempDir.TopoConstraints2")
# Set up the path of the TempDir folder.
dest.dir = paste(getwd(), "/TempDir.TopoConstraints2", sep="")
file.names <- dir(src.dir)
# Copy all the files stored in regPhylo/extdata/TopoConstraints"
# into a temporary folder.
sapply(file.names, function(x) {
file.copy(from = paste(src.dir, x, sep = "/"),
to = paste(dest.dir, x, sep = "/"),
overwrite = FALSE) })

TreeRooted = ape::read.nexus("TempDir.TopoConstraints2/RAxML_bipartitions.Concat_7GTR_Allconst_autoMRE_ReRooted")


### Remove the files in the example that will be created while running the function.
file.remove("TempDir.TopoConstraints2/SimpleXml_Wcont.xml", "TempDir.TopoConstraints2/SimpleXml_2SpNoDNA_Wcont.xml",
            "TempDir.TopoConstraints2/Classif18sp_2NoDNA.csv", "TempDir.TopoConstraints2/BackboneTreeAll_2spNoDNA.txt")


#### Example restricted to taxa with at least a DNA sequence in the supermatrix.

# The input.xml file, called SimpleXml.xml, was prepare by Beauti, it is available
# in the folder "TempDir.TopoConstraints2/xmlfiles". This xml file includes
# the basic template of the xml file (including the supermatrix,
# the partions, the substitution and clock models, the priors,
# the MCMC parameters). However the hard constraints were not
# included in this input.xml file, but will be so by running the
# MultiTopoConst.EditXML4BEAST2 function below.

MultiTopoConst.EditXML4BEAST2(inputtree = TreeRooted,
output = "TempDir.TopoConstraints2/SimpleXml_Wcont.xml",
bootstrapTH = 100, xmltreename = "Subset1",
input.xml = "TempDir.TopoConstraints2/SimpleXml.xml",
Partitions = "TRUE")


test_that("Test the presence of the xml file in the WD", {
  a = readLines("TempDir.TopoConstraints2/SimpleXml_Wcont.xml")
  # test the presence and the file of the xml file exported in the WD
  expect_equal(file.info("TempDir.TopoConstraints2/SimpleXml_Wcont.xml")$size, 83705)
  # Check the number of hard constraint included and monophyletic bloc,
  # must be 12
  expect_equal(length(grep("<distribution id=\"Node", a, fixed = TRUE)), 12)
})


#### Example including taxa without DNA in the supermatrix.

# Load a table with the new taxa without DNA and the topological constraint
# This table will be used to fill the option "TaxaNoDNA".
TaxaNoDNA = cbind(c("Titi_titi", "Toto_toto"), c("Family", "Genus"), c("Congridae", "Scorpaena"))
colnames(TaxaNoDNA) = c("SpeciesName", "hier.level", "ConstraintName")
TaxaNoDNA = as.data.frame(TaxaNoDNA)

# Load the classification table (the same that for the
# ConstraintTaxo2newick function), there are two way to do it:
# either through the .Rdata
data(TopoConstraints) # the second object of the list is the classification table
dim(TopoConstraints[[2]]) # 16 by 23.
# or the classification table has been loaded into the temporary directory,
# and can be loaded into the R environment doing the following
ClassifDF = read.csv("TempDir.TopoConstraints2/Classif16sp.csv", header = TRUE)



# Run the function, but this time the input.xml file called "SimpleXml_2SpNoDNA.xml"
# generated by Beauti must be selected. This xml file template was built using
# an alignment (called "Concat_2spNoDNA_PF2.nex") including two empty sequences
# (i.e. "Titi_titi, "Toto_toto") built by the Align.Concat function.
# This alignment has been completed by the nexus block related to the best
# partition scheme defined by partitionFinder2 (here we used the same
# partition scheme that the one defined for the 16 taxa with at least a DNA sequence).

MultiTopoConst.EditXML4BEAST2(inputtree = TreeRooted,
output = "TempDir.TopoConstraints2/SimpleXml_2SpNoDNA_Wcont.xml",
bootstrapTH = 100, xmltreename = "Subset1",
input.xml = "TempDir.TopoConstraints2/SimpleXml_2SpNoDNA.xml",
Partitions = "TRUE", TaxaNoDNA = TaxaNoDNA,
TaxoTable = ClassifDF,
output.new.TaxoTable = "TempDir.TopoConstraints2/Classif18sp_2NoDNA.csv",
output.new.tree = "TempDir.TopoConstraints2/BackboneTreeAll_2spNoDNA.txt")


test_that("Test the presence of the xml file in the WD, with 2 species without DNA", {
  a = readLines("TempDir.TopoConstraints2/SimpleXml_2SpNoDNA_Wcont.xml")
  # test the presence and the file of the xml file exported in the WD
  expect_equal(file.info("TempDir.TopoConstraints2/SimpleXml_2SpNoDNA_Wcont.xml")$size, 91057)
  # Check the number of hard constraint included and monophyletic bloc,
  # must be 13
  expect_equal(length(grep("<distribution id=\"Node", a, fixed = TRUE)), 13)
})

test_that("Test the export of the new newick tree in WD with 2 species without DNA", {
  test = ape::read.tree("TempDir.TopoConstraints2/BackboneTreeAll_2spNoDNA.txt")
  expect_equal(length(test$tip.label), 18)
  # test that 13 nodes got a value of 100 (hard constraint nodes).
  expect_equal(length(which(test$node.label == "100")), 13)
  # test the presence of 17 node for 18 tip
  expect_equal(test$Nnode, 17)
  # test the fact that the tree should be fully binary (= dichotomic)
  if(ape::is.binary(test)) {b = 1} else {b = 0}
  expect_equal(b, 1)
})

test_that("Test the export of the new classification table with 2 species without DNA", {
  table1 = read.delim("TempDir.TopoConstraints2/Classif18sp_2NoDNA.csv")
  expect_equal(dim(table1)[1], 18)
  expect_equal(dim(table1)[2], 23)
  expect_equal(grep("Titi_titi", table1[,1]), 17)
  if(table1[grep("Titi_titi", table1[,1]), 22] == "Congridae") {c = 1} else {c = 0}
  expect_equal(c, 1)
  if(table1[grep("Titi_titi", table1[,1]), "Order"] == "Anguilliformes") {d = 1} else {d = 0}
  expect_equal(d, 1)
})

rm(ClassifDF, TaxaNoDNA, TreeRooted)

# To clean the files created
unlink("TempDir.TopoConstraints2", recursive = TRUE)






